# Generated by Django 3.0 on 2020-05-24 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
